/********************************************************************
* BCDataSetDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BCDataSetDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBCDataSetDict();
extern void G__cpp_setup_inheritanceBCDataSetDict();
extern void G__cpp_setup_typetableBCDataSetDict();
extern void G__cpp_setup_memvarBCDataSetDict();
extern void G__cpp_setup_globalBCDataSetDict();
extern void G__cpp_setup_memfuncBCDataSetDict();
extern void G__cpp_setup_funcBCDataSetDict();
extern void G__set_cpp_environmentBCDataSetDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../BAT/BCDataSet.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BCDataSetDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__BCDataSetDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BCDataSetDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCDataSetDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BCDataSetDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCDataSetDictLN_BCDataPoint;
extern G__linked_taginfo G__BCDataSetDictLN_vectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgR;
extern G__linked_taginfo G__BCDataSetDictLN_reverse_iteratorlEvectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCDataSetDictLN_BCDataSet;

/* STUB derived class for protected member access */
