//
// File generated by /home/osg/manageTier3SW/ATLASLocalRootBase/i686/root/5.34.07-i686-slc5-gcc4.3/bin/rootcint at Tue Jul  2 14:21:11 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BCEngineMCMCDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BCEngineMCMCDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void BCEngineMCMC_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void BCEngineMCMC_Dictionary();
   static void *new_BCEngineMCMC(void *p = 0);
   static void *newArray_BCEngineMCMC(Long_t size, void *p);
   static void delete_BCEngineMCMC(void *p);
   static void deleteArray_BCEngineMCMC(void *p);
   static void destruct_BCEngineMCMC(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::BCEngineMCMC*)
   {
      ::BCEngineMCMC *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BCEngineMCMC),0);
      static ::ROOT::TGenericClassInfo 
         instance("BCEngineMCMC", "./../BAT/BCEngineMCMC.h", 36,
                  typeid(::BCEngineMCMC), DefineBehavior(ptr, ptr),
                  0, &BCEngineMCMC_Dictionary, isa_proxy, 0,
                  sizeof(::BCEngineMCMC) );
      instance.SetNew(&new_BCEngineMCMC);
      instance.SetNewArray(&newArray_BCEngineMCMC);
      instance.SetDelete(&delete_BCEngineMCMC);
      instance.SetDeleteArray(&deleteArray_BCEngineMCMC);
      instance.SetDestructor(&destruct_BCEngineMCMC);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::BCEngineMCMC*)
   {
      return GenerateInitInstanceLocal((::BCEngineMCMC*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BCEngineMCMC*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BCEngineMCMC_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::BCEngineMCMC*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_BCEngineMCMC(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCEngineMCMC : new ::BCEngineMCMC;
   }
   static void *newArray_BCEngineMCMC(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCEngineMCMC[nElements] : new ::BCEngineMCMC[nElements];
   }
   // Wrapper around operator delete
   static void delete_BCEngineMCMC(void *p) {
      delete ((::BCEngineMCMC*)p);
   }
   static void deleteArray_BCEngineMCMC(void *p) {
      delete [] ((::BCEngineMCMC*)p);
   }
   static void destruct_BCEngineMCMC(void *p) {
      typedef ::BCEngineMCMC current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BCEngineMCMC

/********************************************************
* BCEngineMCMCDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBCEngineMCMCDict();

extern "C" void G__set_cpp_environmentBCEngineMCMCDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../BAT/BCEngineMCMC.h");
  G__cpp_reset_tagtableBCEngineMCMCDict();
}
#include <new>
extern "C" int G__cpp_dllrevBCEngineMCMCDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BCEngineMCMC */
static int G__BCEngineMCMCDict_172_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCEngineMCMC* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCEngineMCMC[n];
     } else {
       p = new((void*) gvp) BCEngineMCMC[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCEngineMCMC;
     } else {
       p = new((void*) gvp) BCEngineMCMC;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMC));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCEngineMCMC* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new BCEngineMCMC((int) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) BCEngineMCMC((int) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMC));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCEngineMCMC* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new BCEngineMCMC(*(BCEngineMCMC*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) BCEngineMCMC(*(BCEngineMCMC*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMC));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const BCEngineMCMC& obj = ((BCEngineMCMC*) G__getstructoffset())->operator=(*(BCEngineMCMC*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNParameters());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNChains());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNLag());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<int>* pobj;
         vector<int> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNIterations();
         pobj = new vector<int>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetCurrentIteration());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetCurrentChain());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNIterationsConvergenceGlobal());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetFlagConvergenceGlobal());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNIterationsMax());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNIterationsRun());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNIterationsPreRunMin());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNIterationsUpdate());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNIterationsUpdateMax());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<int>* pobj;
         vector<int> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNTrialsTrue();
         pobj = new vector<int>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<int>* pobj;
         vector<int> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNTrialsFalse();
         pobj = new vector<int>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetprobMean();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetVariance();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetTrialFunctionScaleFactor();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetTrialFunctionScaleFactor((int) G__int(libp->para[0]));
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetTrialFunctionScaleFactor((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetx();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetx((int) G__int(libp->para[0]));
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetx((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetLogProbx();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetLogProbx((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetPhase());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetCycle());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetMaximumPoints();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetMaximumPoint((int) G__int(libp->para[0]));
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((BCEngineMCMC*) G__getstructoffset())->MCMCGetMaximumLogProb();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetFlagInitialPosition());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetRValueCriterion());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetRValueParametersCriterion());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetRValue());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetRValueParameters((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetRValueStrict());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetFlagRun());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetMarkovChainTree((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetH1Marginalized((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetH2Marginalized((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetTRandom3());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetTrialFunctionScaleFactor(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetNChains((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetNLag((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetNIterationsMax((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetNIterationsRun((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetNIterationsPreRunMin((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetNIterationsUpdate((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetNIterationsUpdateMax((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetMinimumEfficiency((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetMaximumEfficiency((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetWriteChainToFile((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetWritePreRunToFile((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetInitialPositions(*(vector<double>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetInitialPositions(*((vector<std::vector<double> >*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetFlagInitialPosition((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetFlagOrderParameters((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetFlagFillHistograms((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetFlagFillHistograms((int) G__int(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetFlagPreRun((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetRValueCriterion((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetRValueParametersCriterion((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetRValueStrict((bool) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetRValueStrict();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetMarkovChainTrees(*((vector<TTree*>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_69(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCInitializeMarkovChainTrees();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_70(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->SetMarginalized((int) G__int(libp->para[0]), (TH1D*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_71(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->SetMarginalized((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (TH2D*) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_72(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetValuesDefault();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_73(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetValuesQuick();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_74(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetValuesDetail();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_75(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCSetPrecision((BCEngineMCMC::Precision) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_76(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCAddParameter((double) G__double(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_77(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCTrialFunction((int) G__int(libp->para[0]), *(vector<double>*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_78(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCEngineMCMC*) G__getstructoffset())->MCMCTrialFunctionSingle((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_79(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetProposalPointMetropolis((int) G__int(libp->para[0]), *(vector<double>*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_80(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetProposalPointMetropolis((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, *(vector<double>*) libp->para[2].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_81(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letint(result7, 103, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNewPointMetropolis((int) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNewPointMetropolis());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_82(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCGetNewPointMetropolis((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_83(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCInChainCheckMaximum();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_84(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCInChainUpdateStatistics();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_85(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCInChainFillHistograms();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_86(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCInChainTestConvergenceAllChains();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_87(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCInChainWriteChains();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_88(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCEngineMCMC*) G__getstructoffset())->LogEval(*(vector<double>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_89(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCMetropolis());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_90(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCMetropolisPreRun());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_91(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCResetRunStatistics();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_92(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCInitializeMarkovChains();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_93(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCInitialize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_94(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCEngineMCMC*) G__getstructoffset())->MCMCResetResults());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_95(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCIterationInterface();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCEngineMCMCDict_172_0_96(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCEngineMCMC*) G__getstructoffset())->MCMCCurrentPointInterface(*(vector<double>*) libp->para[0].ref, (int) G__int(libp->para[1])
, (bool) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BCEngineMCMC G__TBCEngineMCMC;
static int G__BCEngineMCMCDict_172_0_97(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BCEngineMCMC*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BCEngineMCMC*) (soff+(sizeof(BCEngineMCMC)*i)))->~G__TBCEngineMCMC();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BCEngineMCMC*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BCEngineMCMC*) (soff))->~G__TBCEngineMCMC();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BCEngineMCMC */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBCEngineMCMCDict {
 public:
  G__Sizep2memfuncBCEngineMCMCDict(): p(&G__Sizep2memfuncBCEngineMCMCDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBCEngineMCMCDict::*p)();
};

size_t G__get_sizep2memfuncBCEngineMCMCDict()
{
  G__Sizep2memfuncBCEngineMCMCDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBCEngineMCMCDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBCEngineMCMCDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<double> >",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TTree*>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("MCMCPointerToGetProposalPoint",97,-1,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMC));
   G__setnewtype(-1,"bool (BCEngineMCMC::*MCMCPointerToGetProposalPoint) (int chain, std::vector<double> xnew, std::vector<double> xold) const;",0);
   G__search_typename2("vector<TH1D*>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH2D*>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BCEngineMCMC */
static void G__setup_memvarBCEngineMCMC(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMC));
   { BCEngineMCMC *p; p=(BCEngineMCMC*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMCcLcLPrecision),-1,-2,1,G__FastAllocString(4096).Format("kLow=%lldLL",(long long)BCEngineMCMC::kLow).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMCcLcLPrecision),-1,-2,1,G__FastAllocString(4096).Format("kMedium=%lldLL",(long long)BCEngineMCMC::kMedium).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMCcLcLPrecision),-1,-2,1,G__FastAllocString(4096).Format("kHigh=%lldLL",(long long)BCEngineMCMC::kHigh).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMCcLcLPrecision),-1,-2,1,G__FastAllocString(4096).Format("kVeryHigh=%lldLL",(long long)BCEngineMCMC::kVeryHigh).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,97,0,0,-1,G__defined_typename("MCMCPointerToGetProposalPoint"),-1,4,"fMCMCPointerToGetProposalPoint=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCNParameters=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCBoundaryMin=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCBoundaryMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<bool>"),-1,2,"fMCMCFlagsFillHistograms=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCNChains=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCNLag=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fMCMCNIterations=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCCurrentIteration=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCCurrentChain=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCNIterationsUpdate=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCNIterationsUpdateMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCNIterationsConvergenceGlobal=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fMCMCFlagConvergenceGlobal=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCNIterationsMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCNIterationsRun=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCNIterationsPreRunMin=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fMCMCNTrialsTrue=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fMCMCNTrialsFalse=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fMCMCFlagWriteChainToFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fMCMCFlagWritePreRunToFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCTrialFunctionScaleFactor=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCTrialFunctionScaleFactorStart=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fMCMCFlagPreRun=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fMCMCFlagRun=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCInitialPosition=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fMCMCEfficiencyMin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fMCMCEfficiencyMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCFlagInitialPosition=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fMCMCFlagOrderParameters=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fMCMCFlagFillHistograms=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCPhase=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fMCMCCycle=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCx=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCxMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCxMean=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCxVar=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCxLocal=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCprob=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCprobMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCprobMean=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCprobVar=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fMCMCRValueUseStrict=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fMCMCRValueCriterion=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fMCMCRValueParametersCriterion=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fMCMCRValue=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fMCMCRValueParameters=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_TRandom3),-1,-1,2,"fRandom=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fMCMCH1NBins=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR),G__defined_typename("vector<TH1D*>"),-1,2,"fMCMCH1Marginalized=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR),G__defined_typename("vector<TH2D*>"),-1,2,"fMCMCH2Marginalized=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR),G__defined_typename("vector<TTree*>"),-1,2,"fMCMCTrees=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBCEngineMCMCDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBCEngineMCMC(void) {
   /* BCEngineMCMC */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMC));
   G__memfunc_setup("BCEngineMCMC",1019,G__BCEngineMCMCDict_172_0_1, 105, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMC), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BCEngineMCMC",1019,G__BCEngineMCMCDict_172_0_2, 105, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMC), -1, 0, 1, 1, 1, 0, "i - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BCEngineMCMC",1019,G__BCEngineMCMCDict_172_0_3, 105, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMC), -1, 0, 1, 1, 1, 0, "u 'BCEngineMCMC' - 11 - enginemcmc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__BCEngineMCMCDict_172_0_4, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_BCEngineMCMC), -1, 1, 1, 1, 1, 0, "u 'BCEngineMCMC' - 11 - engineMCMC", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNParameters",1698,G__BCEngineMCMCDict_172_0_5, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNChains",1252,G__BCEngineMCMCDict_172_0_6, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNLag",930,G__BCEngineMCMCDict_172_0_7, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNIterations",1712,G__BCEngineMCMCDict_172_0_8, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetCurrentIteration",2258,G__BCEngineMCMCDict_172_0_9, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetCurrentChain",1798,G__BCEngineMCMCDict_172_0_10, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNIterationsConvergenceGlobal",3440,G__BCEngineMCMCDict_172_0_11, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetFlagConvergenceGlobal",2682,G__BCEngineMCMCDict_172_0_12, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNIterationsMax",2006,G__BCEngineMCMCDict_172_0_13, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNIterationsRun",2021,G__BCEngineMCMCDict_172_0_14, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNIterationsPreRunMin",2608,G__BCEngineMCMCDict_172_0_15, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNIterationsUpdate",2323,G__BCEngineMCMCDict_172_0_16, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNIterationsUpdateMax",2617,G__BCEngineMCMCDict_172_0_17, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNTrialsTrue",1693,G__BCEngineMCMCDict_172_0_18, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNTrialsFalse",1768,G__BCEngineMCMCDict_172_0_19, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetprobMean",1396,G__BCEngineMCMCDict_172_0_20, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetVariance",1385,G__BCEngineMCMCDict_172_0_21, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetTrialFunctionScaleFactor",3017,G__BCEngineMCMCDict_172_0_22, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetTrialFunctionScaleFactor",3017,G__BCEngineMCMCDict_172_0_23, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 1, 1, 1, 0, "i - - 0 - ichain", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetTrialFunctionScaleFactor",3017,G__BCEngineMCMCDict_172_0_24, 100, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - ichain i - - 0 - ipar", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetx",696,G__BCEngineMCMCDict_172_0_25, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetx",696,G__BCEngineMCMCDict_172_0_26, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 1, 1, 1, 0, "i - - 0 - ichain", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetx",696,G__BCEngineMCMCDict_172_0_27, 100, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - ichain i - - 0 - ipar", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetLogProbx",1389,G__BCEngineMCMCDict_172_0_28, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetLogProbx",1389,G__BCEngineMCMCDict_172_0_29, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - ichain", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetPhase",1073,G__BCEngineMCMCDict_172_0_30, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetCycle",1072,G__BCEngineMCMCDict_172_0_31, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetMaximumPoints",1947,G__BCEngineMCMCDict_172_0_32, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetMaximumPoint",1832,G__BCEngineMCMCDict_172_0_33, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetMaximumLogProb",2003,G__BCEngineMCMCDict_172_0_34, 117, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetFlagInitialPosition",2521,G__BCEngineMCMCDict_172_0_35, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetRValueCriterion",2110,G__BCEngineMCMCDict_172_0_36, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetRValueParametersCriterion",3154,G__BCEngineMCMCDict_172_0_37, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetRValue",1167,G__BCEngineMCMCDict_172_0_38, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetRValueParameters",2211,G__BCEngineMCMCDict_172_0_39, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetRValueStrict",1800,G__BCEngineMCMCDict_172_0_40, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetFlagRun",1263,G__BCEngineMCMCDict_172_0_41, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetMarkovChainTree",2083,G__BCEngineMCMCDict_172_0_42, 85, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_TTree), -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetH1Marginalized",1936,G__BCEngineMCMCDict_172_0_43, 85, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_TH1D), -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetH2Marginalized",1937,G__BCEngineMCMCDict_172_0_44, 85, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_TH2D), -1, 0, 2, 1, 1, 0, 
"i - - 0 - i i - - 0 - j", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetTRandom3",1320,G__BCEngineMCMCDict_172_0_45, 85, G__get_linked_tagnum(&G__BCEngineMCMCDictLN_TRandom3), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetTrialFunctionScaleFactor",3029,G__BCEngineMCMCDict_172_0_46, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - scale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetNChains",1264,G__BCEngineMCMCDict_172_0_47, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetNLag",942,G__BCEngineMCMCDict_172_0_48, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetNIterationsMax",2018,G__BCEngineMCMCDict_172_0_49, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetNIterationsRun",2033,G__BCEngineMCMCDict_172_0_50, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetNIterationsPreRunMin",2620,G__BCEngineMCMCDict_172_0_51, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetNIterationsUpdate",2335,G__BCEngineMCMCDict_172_0_52, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetNIterationsUpdateMax",2629,G__BCEngineMCMCDict_172_0_53, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetMinimumEfficiency",2333,G__BCEngineMCMCDict_172_0_54, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - efficiency", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetMaximumEfficiency",2335,G__BCEngineMCMCDict_172_0_55, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - efficiency", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetWriteChainToFile",2173,G__BCEngineMCMCDict_172_0_56, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetWritePreRunToFile",2294,G__BCEngineMCMCDict_172_0_57, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetInitialPositions",2270,G__BCEngineMCMCDict_172_0_58, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 11 - x0s", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetInitialPositions",2270,G__BCEngineMCMCDict_172_0_59, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<std::vector<double> >' 0 - x0s", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetFlagInitialPosition",2533,G__BCEngineMCMCDict_172_0_60, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetFlagOrderParameters",2518,G__BCEngineMCMCDict_172_0_61, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetFlagFillHistograms",2414,G__BCEngineMCMCDict_172_0_62, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetFlagFillHistograms",2414,G__BCEngineMCMCDict_172_0_63, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - index g - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetFlagPreRun",1570,G__BCEngineMCMCDict_172_0_64, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetRValueCriterion",2122,G__BCEngineMCMCDict_172_0_65, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - r", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetRValueParametersCriterion",3166,G__BCEngineMCMCDict_172_0_66, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - r", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetRValueStrict",1812,G__BCEngineMCMCDict_172_0_67, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'true' strict", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetMarkovChainTrees",2210,G__BCEngineMCMCDict_172_0_68, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<TTree*,allocator<TTree*> >' 'vector<TTree*>' 0 - trees", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCInitializeMarkovChainTrees",2952,G__BCEngineMCMCDict_172_0_69, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMarginalized",1539,G__BCEngineMCMCDict_172_0_70, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - index U 'TH1D' - 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMarginalized",1539,G__BCEngineMCMCDict_172_0_71, 105, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - index1 i - - 0 - index2 "
"U 'TH2D' - 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetValuesDefault",1921,G__BCEngineMCMCDict_172_0_72, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetValuesQuick",1721,G__BCEngineMCMCDict_172_0_73, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetValuesDetail",1807,G__BCEngineMCMCDict_172_0_74, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCSetPrecision",1528,G__BCEngineMCMCDict_172_0_75, 121, -1, -1, 0, 1, 1, 1, 0, "i 'BCEngineMCMC::Precision' - 0 - precision", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCAddParameter",1482,G__BCEngineMCMCDict_172_0_76, 105, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - min d - - 0 - max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCTrialFunction",1634,G__BCEngineMCMCDict_172_0_77, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - ichain u 'vector<double,allocator<double> >' 'vector<double>' 1 - x", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("MCMCTrialFunctionSingle",2244,G__BCEngineMCMCDict_172_0_78, 100, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - ichain i - - 0 - ipar", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("MCMCGetProposalPointMetropolis",3016,G__BCEngineMCMCDict_172_0_79, 103, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - chain u 'vector<double,allocator<double> >' 'vector<double>' 1 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetProposalPointMetropolis",3016,G__BCEngineMCMCDict_172_0_80, 103, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - chain i - - 0 - parameter "
"u 'vector<double,allocator<double> >' 'vector<double>' 1 - x", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNewPointMetropolis",2466,G__BCEngineMCMCDict_172_0_81, 103, -1, -1, 0, 1, 1, 1, 0, "i - - 0 '0' chain", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCGetNewPointMetropolis",2466,G__BCEngineMCMCDict_172_0_82, 103, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - chain i - - 0 - parameter", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCInChainCheckMaximum",2166,G__BCEngineMCMCDict_172_0_83, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCInChainUpdateStatistics",2632,G__BCEngineMCMCDict_172_0_84, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCInChainFillHistograms",2402,G__BCEngineMCMCDict_172_0_85, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCInChainTestConvergenceAllChains",3384,G__BCEngineMCMCDict_172_0_86, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCInChainWriteChains",2075,G__BCEngineMCMCDict_172_0_87, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LogEval",682,G__BCEngineMCMCDict_172_0_88, 100, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("MCMCMetropolis",1358,G__BCEngineMCMCDict_172_0_89, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCMetropolisPreRun",1962,G__BCEngineMCMCDict_172_0_90, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCResetRunStatistics",2179,G__BCEngineMCMCDict_172_0_91, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCInitializeMarkovChains",2552,G__BCEngineMCMCDict_172_0_92, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCInitialize",1330,G__BCEngineMCMCDict_172_0_93, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCResetResults",1557,G__BCEngineMCMCDict_172_0_94, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCIterationInterface",2144,G__BCEngineMCMCDict_172_0_95, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("MCMCCurrentPointInterface",2462,G__BCEngineMCMCDict_172_0_96, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<double,allocator<double> >' 'vector<double>' 1 - point i - - 0 - ichain "
"g - - 0 - accepted", (char*)NULL, (void*) NULL, 1);
   // automatic destructor
   G__memfunc_setup("~BCEngineMCMC", 1145, G__BCEngineMCMCDict_172_0_97, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBCEngineMCMCDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBCEngineMCMCDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBCEngineMCMCDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_vectorlEboolcOallocatorlEboolgRsPgR = { "vector<bool,allocator<bool> >" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_TH2D = { "TH2D" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_TRandom3 = { "TRandom3" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_BCEngineMCMC = { "BCEngineMCMC" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_BCEngineMCMCcLcLPrecision = { "BCEngineMCMC::Precision" , 101 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR = { "vector<TTree*,allocator<TTree*> >" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TTree*,allocator<TTree*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR = { "vector<TH1D*,allocator<TH1D*> >" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1D*,allocator<TH1D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR = { "vector<TH2D*,allocator<TH2D*> >" , 99 , -1 };
G__linked_taginfo G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH2D*,allocator<TH2D*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBCEngineMCMCDict() {
  G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_vectorlEboolcOallocatorlEboolgRsPgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_TH1D.tagnum = -1 ;
  G__BCEngineMCMCDictLN_TH2D.tagnum = -1 ;
  G__BCEngineMCMCDictLN_TTree.tagnum = -1 ;
  G__BCEngineMCMCDictLN_TRandom3.tagnum = -1 ;
  G__BCEngineMCMCDictLN_BCEngineMCMC.tagnum = -1 ;
  G__BCEngineMCMCDictLN_BCEngineMCMCcLcLPrecision.tagnum = -1 ;
  G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR.tagnum = -1 ;
  G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBCEngineMCMCDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_vectorlEboolcOallocatorlEboolgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_TH2D);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_TRandom3);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_BCEngineMCMC),sizeof(BCEngineMCMC),-1,36608,(char*)NULL,G__setup_memvarBCEngineMCMC,G__setup_memfuncBCEngineMCMC);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_BCEngineMCMCcLcLPrecision);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCEngineMCMCDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupBCEngineMCMCDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupBCEngineMCMCDict()");
  G__set_cpp_environmentBCEngineMCMCDict();
  G__cpp_setup_tagtableBCEngineMCMCDict();

  G__cpp_setup_inheritanceBCEngineMCMCDict();

  G__cpp_setup_typetableBCEngineMCMCDict();

  G__cpp_setup_memvarBCEngineMCMCDict();

  G__cpp_setup_memfuncBCEngineMCMCDict();
  G__cpp_setup_globalBCEngineMCMCDict();
  G__cpp_setup_funcBCEngineMCMCDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBCEngineMCMCDict();
  return;
}
class G__cpp_setup_initBCEngineMCMCDict {
  public:
    G__cpp_setup_initBCEngineMCMCDict() { G__add_setup_func("BCEngineMCMCDict",(G__incsetup)(&G__cpp_setupBCEngineMCMCDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBCEngineMCMCDict() { G__remove_setup_func("BCEngineMCMCDict"); }
};
G__cpp_setup_initBCEngineMCMCDict G__cpp_setup_initializerBCEngineMCMCDict;

