/********************************************************************
* BCIntegrateDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BCIntegrateDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBCIntegrateDict();
extern void G__cpp_setup_inheritanceBCIntegrateDict();
extern void G__cpp_setup_typetableBCIntegrateDict();
extern void G__cpp_setup_memvarBCIntegrateDict();
extern void G__cpp_setup_globalBCIntegrateDict();
extern void G__cpp_setup_memfuncBCIntegrateDict();
extern void G__cpp_setup_funcBCIntegrateDict();
extern void G__set_cpp_environmentBCIntegrateDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../BAT/BCIntegrate.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BCIntegrateDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__BCIntegrateDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__BCIntegrateDictLN_string;
extern G__linked_taginfo G__BCIntegrateDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BCIntegrateDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCIntegrateDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BCIntegrateDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCIntegrateDictLN_TH1D;
extern G__linked_taginfo G__BCIntegrateDictLN_TH2D;
extern G__linked_taginfo G__BCIntegrateDictLN_TTree;
extern G__linked_taginfo G__BCIntegrateDictLN_BCEngineMCMC;
extern G__linked_taginfo G__BCIntegrateDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__BCIntegrateDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCIntegrateDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__BCIntegrateDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCIntegrateDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR;
extern G__linked_taginfo G__BCIntegrateDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCIntegrateDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR;
extern G__linked_taginfo G__BCIntegrateDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCIntegrateDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR;
extern G__linked_taginfo G__BCIntegrateDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCIntegrateDictLN_BCParameter;
extern G__linked_taginfo G__BCIntegrateDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR;
extern G__linked_taginfo G__BCIntegrateDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCIntegrateDictLN_BCDataPoint;
extern G__linked_taginfo G__BCIntegrateDictLN_TMinuit;
extern G__linked_taginfo G__BCIntegrateDictLN_BCIntegrate;
extern G__linked_taginfo G__BCIntegrateDictLN_BCIntegratecLcLBCIntegrationMethod;
extern G__linked_taginfo G__BCIntegrateDictLN_BCIntegratecLcLBCMarginalizationMethod;
extern G__linked_taginfo G__BCIntegrateDictLN_BCIntegratecLcLBCOptimizationMethod;
extern G__linked_taginfo G__BCIntegrateDictLN_BCIntegratecLcLBCSASchedule;
extern G__linked_taginfo G__BCIntegrateDictLN_BCIntegratecLcLBCCubaMethod;

/* STUB derived class for protected member access */
