/********************************************************************
* BCMathDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BCMathDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBCMathDict();
extern void G__cpp_setup_inheritanceBCMathDict();
extern void G__cpp_setup_typetableBCMathDict();
extern void G__cpp_setup_memvarBCMathDict();
extern void G__cpp_setup_globalBCMathDict();
extern void G__cpp_setup_memfuncBCMathDict();
extern void G__cpp_setup_funcBCMathDict();
extern void G__set_cpp_environmentBCMathDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../BAT/BCMath.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BCMathDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__BCMathDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__BCMathDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BCMathDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMathDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BCMathDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMathDictLN_TH1D;
extern G__linked_taginfo G__BCMathDictLN_BCMath;
extern G__linked_taginfo G__BCMathDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__BCMathDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
