//
// File generated by /home/osg/manageTier3SW/ATLASLocalRootBase/i686/root/5.34.07-i686-slc5-gcc4.3/bin/rootcint at Tue Jul  2 14:21:16 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BCModelManagerDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BCModelManagerDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void BCModelManager_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void BCModelManager_Dictionary();
   static void *new_BCModelManager(void *p = 0);
   static void *newArray_BCModelManager(Long_t size, void *p);
   static void delete_BCModelManager(void *p);
   static void deleteArray_BCModelManager(void *p);
   static void destruct_BCModelManager(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::BCModelManager*)
   {
      ::BCModelManager *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BCModelManager),0);
      static ::ROOT::TGenericClassInfo 
         instance("BCModelManager", "./../BAT/BCModelManager.h", 35,
                  typeid(::BCModelManager), DefineBehavior(ptr, ptr),
                  0, &BCModelManager_Dictionary, isa_proxy, 0,
                  sizeof(::BCModelManager) );
      instance.SetNew(&new_BCModelManager);
      instance.SetNewArray(&newArray_BCModelManager);
      instance.SetDelete(&delete_BCModelManager);
      instance.SetDeleteArray(&deleteArray_BCModelManager);
      instance.SetDestructor(&destruct_BCModelManager);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::BCModelManager*)
   {
      return GenerateInitInstanceLocal((::BCModelManager*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BCModelManager*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BCModelManager_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::BCModelManager*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_BCModelManager(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCModelManager : new ::BCModelManager;
   }
   static void *newArray_BCModelManager(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCModelManager[nElements] : new ::BCModelManager[nElements];
   }
   // Wrapper around operator delete
   static void delete_BCModelManager(void *p) {
      delete ((::BCModelManager*)p);
   }
   static void deleteArray_BCModelManager(void *p) {
      delete [] ((::BCModelManager*)p);
   }
   static void destruct_BCModelManager(void *p) {
      typedef ::BCModelManager current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BCModelManager

/********************************************************
* BCModelManagerDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBCModelManagerDict();

extern "C" void G__set_cpp_environmentBCModelManagerDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../BAT/BCModelManager.h");
  G__cpp_reset_tagtableBCModelManagerDict();
}
#include <new>
extern "C" int G__cpp_dllrevBCModelManagerDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BCModelManager */
static int G__BCModelManagerDict_228_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCModelManager* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCModelManager[n];
     } else {
       p = new((void*) gvp) BCModelManager[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCModelManager;
     } else {
       p = new((void*) gvp) BCModelManager;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCModelManagerDictLN_BCModelManager));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCModelManager* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new BCModelManager(*(BCModelManager*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) BCModelManager(*(BCModelManager*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCModelManagerDictLN_BCModelManager));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const BCModelManager& obj = ((BCModelManager*) G__getstructoffset())->operator=(*(BCModelManager*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((BCModelManager*) G__getstructoffset())->GetNModels());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCModelManager*) G__getstructoffset())->GetModel((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCModelManager*) G__getstructoffset())->GetNDataPoints());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCModelManager*) G__getstructoffset())->GetDataPoint((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCModelManager*) G__getstructoffset())->GetDataSet());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetDataSet((BCDataSet*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetSingleDataPoint((BCDataPoint*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetSingleDataPoint((BCDataSet*) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetMarginalizationMethod((BCIntegrate::BCMarginalizationMethod) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetIntegrationMethod((BCIntegrate::BCIntegrationMethod) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetOptimizationMethod((BCIntegrate::BCOptimizationMethod) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetNiterationsPerDimension((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetNSamplesPer2DBin((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetRelativePrecision((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetNbins((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((BCModelManager*) G__getstructoffset())->SetFillErrorBand((bool) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((BCModelManager*) G__getstructoffset())->SetFillErrorBand();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->UnetFillErrorBand();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetFitFunctionIndexX((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetFitFunctionIndexY((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetFitFunctionIndices((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetDataPointLowerBoundaries((BCDataPoint*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetDataPointUpperBoundaries((BCDataPoint*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetDataPointLowerBoundary((int) G__int(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetDataPointUpperBoundary((int) G__int(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetDataBoundaries((int) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->FixDataAxis((int) G__int(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->SetNChains((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((BCModelManager*) G__getstructoffset())->AddModel((BCModel*) G__int(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((BCModelManager*) G__getstructoffset())->AddModel((BCModel*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->AddDataPoint((BCDataPoint*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCModelManager*) G__getstructoffset())->ReadDataFromFile((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCModelManager*) G__getstructoffset())->ReadDataFromFile((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCModelManager*) G__getstructoffset())->ReadDataFromFileTree((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCModelManager*) G__getstructoffset())->ReadDataFromFileTxt((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->Normalize();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCModelManager*) G__getstructoffset())->BayesFactor((const unsigned int) G__int(libp->para[0]), (const unsigned int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->FindMode();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->MarginalizeAll();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->WriteMarkovChain((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->ResetDataSet();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((BCModelManager*) G__getstructoffset())->PrintModelComparisonSummary((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((BCModelManager*) G__getstructoffset())->PrintModelComparisonSummary();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((BCModelManager*) G__getstructoffset())->PrintSummary((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((BCModelManager*) G__getstructoffset())->PrintSummary();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCModelManager*) G__getstructoffset())->PrintResults();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCModelManagerDict_228_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((BCModelManager*) G__getstructoffset())->CalculatePValue((bool) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((BCModelManager*) G__getstructoffset())->CalculatePValue();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BCModelManager G__TBCModelManager;
static int G__BCModelManagerDict_228_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BCModelManager*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BCModelManager*) (soff+(sizeof(BCModelManager)*i)))->~G__TBCModelManager();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BCModelManager*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BCModelManager*) (soff))->~G__TBCModelManager();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BCModelManager */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBCModelManagerDict {
 public:
  G__Sizep2memfuncBCModelManagerDict(): p(&G__Sizep2memfuncBCModelManagerDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBCModelManagerDict::*p)();
};

size_t G__get_sizep2memfuncBCModelManagerDict()
{
  G__Sizep2memfuncBCModelManagerDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBCModelManagerDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBCModelManagerDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<double> >",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TTree*>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1D*>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH2D*>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCParameter*>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TNamed*>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCModel*>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCDataPoint*>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BCModelManager */
static void G__setup_memvarBCModelManager(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BCModelManagerDictLN_BCModelManager));
   { BCModelManager *p; p=(BCModelManager*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCModelManagerDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR),G__defined_typename("BCModelContainer"),-1,4,"fModelContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCModelManagerDictLN_BCDataSet),-1,-1,4,"fDataSet=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBCModelManagerDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBCModelManager(void) {
   /* BCModelManager */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BCModelManagerDictLN_BCModelManager));
   G__memfunc_setup("BCModelManager",1329,G__BCModelManagerDict_228_0_1, 105, G__get_linked_tagnum(&G__BCModelManagerDictLN_BCModelManager), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BCModelManager",1329,G__BCModelManagerDict_228_0_2, 105, G__get_linked_tagnum(&G__BCModelManagerDictLN_BCModelManager), -1, 0, 1, 1, 1, 0, "u 'BCModelManager' - 11 - modelmanager", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__BCModelManagerDict_228_0_3, 117, G__get_linked_tagnum(&G__BCModelManagerDictLN_BCModelManager), -1, 1, 1, 1, 1, 0, "u 'BCModelManager' - 11 - modelmanager", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNModels",978,G__BCModelManagerDict_228_0_4, 104, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetModel",785,G__BCModelManagerDict_228_0_5, 85, G__get_linked_tagnum(&G__BCModelManagerDictLN_BCModel), -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNDataPoints",1381,G__BCModelManagerDict_228_0_6, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDataPoint",1188,G__BCModelManagerDict_228_0_7, 85, G__get_linked_tagnum(&G__BCModelManagerDictLN_BCDataPoint), -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDataSet",966,G__BCModelManagerDict_228_0_8, 85, G__get_linked_tagnum(&G__BCModelManagerDictLN_BCDataSet), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDataSet",978,G__BCModelManagerDict_228_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "U 'BCDataSet' - 0 - dataset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSingleDataPoint",1810,G__BCModelManagerDict_228_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "U 'BCDataPoint' - 0 - datapoint", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSingleDataPoint",1810,G__BCModelManagerDict_228_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'BCDataSet' - 0 - dataset h - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMarginalizationMethod",2486,G__BCModelManagerDict_228_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "i 'BCIntegrate::BCMarginalizationMethod' - 0 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetIntegrationMethod",2065,G__BCModelManagerDict_228_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "i 'BCIntegrate::BCIntegrationMethod' - 0 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetOptimizationMethod",2196,G__BCModelManagerDict_228_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "i 'BCIntegrate::BCOptimizationMethod' - 0 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNiterationsPerDimension",2697,G__BCModelManagerDict_228_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - niterations", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNSamplesPer2DBin",1797,G__BCModelManagerDict_228_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRelativePrecision",2068,G__BCModelManagerDict_228_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - relprecision", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNbins",806,G__BCModelManagerDict_228_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFillErrorBand",1586,G__BCModelManagerDict_228_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'true' flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UnetFillErrorBand",1698,G__BCModelManagerDict_228_0_20, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFitFunctionIndexX",2021,G__BCModelManagerDict_228_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFitFunctionIndexY",2022,G__BCModelManagerDict_228_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFitFunctionIndices",2132,G__BCModelManagerDict_228_0_23, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - indexx i - - 0 - indexy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDataPointLowerBoundaries",2757,G__BCModelManagerDict_228_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "U 'BCDataPoint' - 0 - datasetlowerboundaries", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDataPointUpperBoundaries",2760,G__BCModelManagerDict_228_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "U 'BCDataPoint' - 0 - datasetupperboundaries", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDataPointLowerBoundary",2557,G__BCModelManagerDict_228_0_26, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - index d - - 0 - lowerboundary", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDataPointUpperBoundary",2560,G__BCModelManagerDict_228_0_27, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - index d - - 0 - upperboundary", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDataBoundaries",1714,G__BCModelManagerDict_228_0_28, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - index d - - 0 - lowerboundary "
"d - - 0 - upperboundary", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FixDataAxis",1078,G__BCModelManagerDict_228_0_29, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - index g - - 0 - fixed", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNChains",976,G__BCModelManagerDict_228_0_30, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddModel",762,G__BCModelManagerDict_228_0_31, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'BCModel' - 0 - model d - - 0 '0.' probability", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddDataPoint",1165,G__BCModelManagerDict_228_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "U 'BCDataPoint' - 0 - datapoint", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadDataFromFile",1546,G__BCModelManagerDict_228_0_33, 105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - filename C - - 10 - treename "
"C - - 10 - branchnames", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadDataFromFile",1546,G__BCModelManagerDict_228_0_34, 105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - filename i - - 0 - nvariables", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadDataFromFileTree",1946,G__BCModelManagerDict_228_0_35, 105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - filename C - - 10 - treename "
"C - - 10 - branchnames", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadDataFromFileTxt",1866,G__BCModelManagerDict_228_0_36, 105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - filename i - - 0 - nbranches", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Normalize",945,G__BCModelManagerDict_228_0_37, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BayesFactor",1107,G__BCModelManagerDict_228_0_38, 100, -1, -1, 0, 2, 1, 1, 0, 
"h - - 10 - imodel1 h - - 10 - imodel2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FindMode",774,G__BCModelManagerDict_228_0_39, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MarginalizeAll",1420,G__BCModelManagerDict_228_0_40, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("WriteMarkovChain",1630,G__BCModelManagerDict_228_0_41, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ResetDataSet",1193,G__BCModelManagerDict_228_0_42, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintModelComparisonSummary",2823,G__BCModelManagerDict_228_0_43, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 '0' filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintSummary",1275,G__BCModelManagerDict_228_0_44, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 '0' filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintResults",1279,G__BCModelManagerDict_228_0_45, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculatePValue",1499,G__BCModelManagerDict_228_0_46, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'false' flag_histogram", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Copy",411,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 8, "u 'BCModelManager' - 1 - modelmanager", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BCModelManager", 1455, G__BCModelManagerDict_228_0_48, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBCModelManagerDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBCModelManagerDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBCModelManagerDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BCModelManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR = { "vector<TTree*,allocator<TTree*> >" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TTree*,allocator<TTree*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR = { "vector<TH1D*,allocator<TH1D*> >" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1D*,allocator<TH1D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR = { "vector<TH2D*,allocator<TH2D*> >" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH2D*,allocator<TH2D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR = { "vector<BCParameter*,allocator<BCParameter*> >" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCParameter*,allocator<BCParameter*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_BCDataPoint = { "BCDataPoint" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_BCIntegrate = { "BCIntegrate" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_BCIntegratecLcLBCIntegrationMethod = { "BCIntegrate::BCIntegrationMethod" , 101 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_BCIntegratecLcLBCMarginalizationMethod = { "BCIntegrate::BCMarginalizationMethod" , 101 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_BCIntegratecLcLBCOptimizationMethod = { "BCIntegrate::BCOptimizationMethod" , 101 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_BCDataSet = { "BCDataSet" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_BCModel = { "BCModel" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR = { "vector<TNamed*,allocator<TNamed*> >" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TNamed*,allocator<TNamed*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR = { "vector<BCModel*,allocator<BCModel*> >" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCModel*,allocator<BCModel*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_vectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgR = { "vector<BCDataPoint*,allocator<BCDataPoint*> >" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCDataPoint*,allocator<BCDataPoint*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCModelManagerDictLN_BCModelManager = { "BCModelManager" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBCModelManagerDict() {
  G__BCModelManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BCModelManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCModelManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BCModelManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCModelManagerDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__BCModelManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCModelManagerDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__BCModelManagerDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCModelManagerDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR.tagnum = -1 ;
  G__BCModelManagerDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCModelManagerDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR.tagnum = -1 ;
  G__BCModelManagerDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCModelManagerDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR.tagnum = -1 ;
  G__BCModelManagerDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCModelManagerDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR.tagnum = -1 ;
  G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCModelManagerDictLN_BCDataPoint.tagnum = -1 ;
  G__BCModelManagerDictLN_BCIntegrate.tagnum = -1 ;
  G__BCModelManagerDictLN_BCIntegratecLcLBCIntegrationMethod.tagnum = -1 ;
  G__BCModelManagerDictLN_BCIntegratecLcLBCMarginalizationMethod.tagnum = -1 ;
  G__BCModelManagerDictLN_BCIntegratecLcLBCOptimizationMethod.tagnum = -1 ;
  G__BCModelManagerDictLN_BCDataSet.tagnum = -1 ;
  G__BCModelManagerDictLN_BCModel.tagnum = -1 ;
  G__BCModelManagerDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR.tagnum = -1 ;
  G__BCModelManagerDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCModelManagerDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR.tagnum = -1 ;
  G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCModelManagerDictLN_vectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgR.tagnum = -1 ;
  G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCModelManagerDictLN_BCModelManager.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBCModelManagerDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_BCDataPoint);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_BCIntegrate);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_BCIntegratecLcLBCIntegrationMethod);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_BCIntegratecLcLBCMarginalizationMethod);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_BCIntegratecLcLBCOptimizationMethod);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_BCDataSet);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_BCModel);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_vectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_reverse_iteratorlEvectorlEBCDataPointmUcOallocatorlEBCDataPointmUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BCModelManagerDictLN_BCModelManager),sizeof(BCModelManager),-1,3840,(char*)NULL,G__setup_memvarBCModelManager,G__setup_memfuncBCModelManager);
}
extern "C" void G__cpp_setupBCModelManagerDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupBCModelManagerDict()");
  G__set_cpp_environmentBCModelManagerDict();
  G__cpp_setup_tagtableBCModelManagerDict();

  G__cpp_setup_inheritanceBCModelManagerDict();

  G__cpp_setup_typetableBCModelManagerDict();

  G__cpp_setup_memvarBCModelManagerDict();

  G__cpp_setup_memfuncBCModelManagerDict();
  G__cpp_setup_globalBCModelManagerDict();
  G__cpp_setup_funcBCModelManagerDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBCModelManagerDict();
  return;
}
class G__cpp_setup_initBCModelManagerDict {
  public:
    G__cpp_setup_initBCModelManagerDict() { G__add_setup_func("BCModelManagerDict",(G__incsetup)(&G__cpp_setupBCModelManagerDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBCModelManagerDict() { G__remove_setup_func("BCModelManagerDict"); }
};
G__cpp_setup_initBCModelManagerDict G__cpp_setup_initializerBCModelManagerDict;

