//
// File generated by /home/osg/manageTier3SW/ATLASLocalRootBase/i686/root/5.34.07-i686-slc5-gcc4.3/bin/rootcint at Tue Jul  2 14:21:21 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BCSummaryToolDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BCSummaryToolDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void BCSummaryTool_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void BCSummaryTool_Dictionary();
   static void *new_BCSummaryTool(void *p = 0);
   static void *newArray_BCSummaryTool(Long_t size, void *p);
   static void delete_BCSummaryTool(void *p);
   static void deleteArray_BCSummaryTool(void *p);
   static void destruct_BCSummaryTool(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::BCSummaryTool*)
   {
      ::BCSummaryTool *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BCSummaryTool),0);
      static ::ROOT::TGenericClassInfo 
         instance("BCSummaryTool", "./../BAT/BCSummaryTool.h", 34,
                  typeid(::BCSummaryTool), DefineBehavior(ptr, ptr),
                  0, &BCSummaryTool_Dictionary, isa_proxy, 0,
                  sizeof(::BCSummaryTool) );
      instance.SetNew(&new_BCSummaryTool);
      instance.SetNewArray(&newArray_BCSummaryTool);
      instance.SetDelete(&delete_BCSummaryTool);
      instance.SetDeleteArray(&deleteArray_BCSummaryTool);
      instance.SetDestructor(&destruct_BCSummaryTool);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::BCSummaryTool*)
   {
      return GenerateInitInstanceLocal((::BCSummaryTool*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BCSummaryTool*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BCSummaryTool_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::BCSummaryTool*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_BCSummaryTool(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCSummaryTool : new ::BCSummaryTool;
   }
   static void *newArray_BCSummaryTool(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCSummaryTool[nElements] : new ::BCSummaryTool[nElements];
   }
   // Wrapper around operator delete
   static void delete_BCSummaryTool(void *p) {
      delete ((::BCSummaryTool*)p);
   }
   static void deleteArray_BCSummaryTool(void *p) {
      delete [] ((::BCSummaryTool*)p);
   }
   static void destruct_BCSummaryTool(void *p) {
      typedef ::BCSummaryTool current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BCSummaryTool

/********************************************************
* BCSummaryToolDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBCSummaryToolDict();

extern "C" void G__set_cpp_environmentBCSummaryToolDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../BAT/BCSummaryTool.h");
  G__cpp_reset_tagtableBCSummaryToolDict();
}
#include <new>
extern "C" int G__cpp_dllrevBCSummaryToolDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BCSummaryTool */
static int G__BCSummaryToolDict_170_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCSummaryTool* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCSummaryTool[n];
     } else {
       p = new((void*) gvp) BCSummaryTool[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCSummaryTool;
     } else {
       p = new((void*) gvp) BCSummaryTool;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCSummaryTool));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCSummaryTool* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new BCSummaryTool((BCModel*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) BCSummaryTool((BCModel*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCSummaryTool));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCSummaryTool*) G__getstructoffset())->GetPriorModel());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCSummaryTool*) G__getstructoffset())->SetModel((BCModel*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->CalculatePriorModel());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->CopySummaryData());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintParameterPlot((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintParameterPlot());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintCorrelationMatrix((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintCorrelationMatrix());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintCorrelationPlot((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintCorrelationPlot());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->DrawKnowledgeUpdatePlot1D((int) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->DrawKnowledgeUpdatePlot1D((int) G__int(libp->para[0]), (double) G__double(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->DrawKnowledgeUpdatePlot1D((int) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintKnowledgeUpdatePlot1D((int) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintKnowledgeUpdatePlot1D((int) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (double) G__double(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintKnowledgeUpdatePlot1D((int) G__int(libp->para[0]), (const char*) G__int(libp->para[1])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintKnowledgeUpdatePlots((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintKnowledgeUpdatePlots());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintParameterSummary());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintCorrelationSummary());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintParameterLatex((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCSummaryToolDict_170_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCSummaryTool*) G__getstructoffset())->PrintCorrelationLatex());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BCSummaryToolDict_170_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BCSummaryTool* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BCSummaryTool(*(BCSummaryTool*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCSummaryTool));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BCSummaryTool G__TBCSummaryTool;
static int G__BCSummaryToolDict_170_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BCSummaryTool*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BCSummaryTool*) (soff+(sizeof(BCSummaryTool)*i)))->~G__TBCSummaryTool();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BCSummaryTool*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BCSummaryTool*) (soff))->~G__TBCSummaryTool();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BCSummaryToolDict_170_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCSummaryTool* dest = (BCSummaryTool*) G__getstructoffset();
   *dest = *(BCSummaryTool*) libp->para[0].ref;
   const BCSummaryTool& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BCSummaryTool */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBCSummaryToolDict {
 public:
  G__Sizep2memfuncBCSummaryToolDict(): p(&G__Sizep2memfuncBCSummaryToolDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBCSummaryToolDict::*p)();
};

size_t G__get_sizep2memfuncBCSummaryToolDict()
{
  G__Sizep2memfuncBCSummaryToolDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBCSummaryToolDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBCSummaryToolDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCSummaryToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCSummaryToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCSummaryToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCSummaryToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCSummaryToolDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCSummaryToolDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BCSummaryTool */
static void G__setup_memvarBCSummaryTool(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCSummaryTool));
   { BCSummaryTool *p; p=(BCSummaryTool*)0x1000; if (p) { }
   G__memvar_setup((void*)0,104,0,0,-1,-1,-2,4,"fHCounter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCModel),-1,-1,4,"fModel=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,4,"fParName=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fParMin=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fParMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fCorrCoeff=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fMargMode=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fMean=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fGlobalMode=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fQuantiles=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fSmallInt=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fRMS=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fSumProb=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCSummaryPriorModel),-1,-1,4,"fPriorModel=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fFlagInfoMarg=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fFlagInfoOpt=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBCSummaryToolDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBCSummaryTool(void) {
   /* BCSummaryTool */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCSummaryTool));
   G__memfunc_setup("BCSummaryTool",1297,G__BCSummaryToolDict_170_0_1, 105, G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCSummaryTool), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BCSummaryTool",1297,G__BCSummaryToolDict_170_0_2, 105, G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCSummaryTool), -1, 0, 1, 1, 1, 0, "U 'BCModel' - 0 - model", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPriorModel",1309,G__BCSummaryToolDict_170_0_3, 85, G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCSummaryPriorModel), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetModel",797,G__BCSummaryToolDict_170_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "U 'BCModel' - 0 - model", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculatePriorModel",1931,G__BCSummaryToolDict_170_0_5, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CopySummaryData",1539,G__BCSummaryToolDict_170_0_6, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintParameterPlot",1869,G__BCSummaryToolDict_170_0_7, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 '\"parameters.eps\"' filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintCorrelationMatrix",2308,G__BCSummaryToolDict_170_0_8, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 '\"matrix.eps\"' filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintCorrelationPlot",2094,G__BCSummaryToolDict_170_0_9, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 '\"correlation.eps\"' filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawKnowledgeUpdatePlot1D",2469,G__BCSummaryToolDict_170_0_10, 105, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - index d - - 0 '0.' min "
"d - - 0 '0.' max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintKnowledgeUpdatePlot1D",2596,G__BCSummaryToolDict_170_0_11, 105, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - index C - - 10 - filename "
"d - - 0 '0.' min d - - 0 '0.' max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintKnowledgeUpdatePlots",2594,G__BCSummaryToolDict_170_0_12, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 '\"update.ps\"' filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintParameterSummary",2204,G__BCSummaryToolDict_170_0_13, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintCorrelationSummary",2429,G__BCSummaryToolDict_170_0_14, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintParameterLatex",1964,G__BCSummaryToolDict_170_0_15, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintCorrelationLatex",2189,G__BCSummaryToolDict_170_0_16, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getNextIndex",1239,(G__InterfaceMethod) NULL, 104, -1, -1, 0, 0, 3, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("BCSummaryTool", 1297, G__BCSummaryToolDict_170_0_18, (int) ('i'), G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCSummaryTool), -1, 0, 1, 1, 1, 0, "u 'BCSummaryTool' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BCSummaryTool", 1423, G__BCSummaryToolDict_170_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BCSummaryToolDict_170_0_20, (int) ('u'), G__get_linked_tagnum(&G__BCSummaryToolDictLN_BCSummaryTool), -1, 1, 1, 1, 1, 0, "u 'BCSummaryTool' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBCSummaryToolDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBCSummaryToolDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBCSummaryToolDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__BCSummaryToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BCSummaryToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCSummaryToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BCSummaryToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCSummaryToolDictLN_BCModel = { "BCModel" , 99 , -1 };
G__linked_taginfo G__BCSummaryToolDictLN_BCSummaryPriorModel = { "BCSummaryPriorModel" , 99 , -1 };
G__linked_taginfo G__BCSummaryToolDictLN_BCSummaryTool = { "BCSummaryTool" , 99 , -1 };
G__linked_taginfo G__BCSummaryToolDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__BCSummaryToolDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBCSummaryToolDict() {
  G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__BCSummaryToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BCSummaryToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCSummaryToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BCSummaryToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCSummaryToolDictLN_BCModel.tagnum = -1 ;
  G__BCSummaryToolDictLN_BCSummaryPriorModel.tagnum = -1 ;
  G__BCSummaryToolDictLN_BCSummaryTool.tagnum = -1 ;
  G__BCSummaryToolDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__BCSummaryToolDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBCSummaryToolDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BCSummaryToolDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__BCSummaryToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BCSummaryToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCSummaryToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCSummaryToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCSummaryToolDictLN_BCModel);
   G__get_linked_tagnum_fwd(&G__BCSummaryToolDictLN_BCSummaryPriorModel);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BCSummaryToolDictLN_BCSummaryTool),sizeof(BCSummaryTool),-1,34048,(char*)NULL,G__setup_memvarBCSummaryTool,G__setup_memfuncBCSummaryTool);
   G__get_linked_tagnum_fwd(&G__BCSummaryToolDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCSummaryToolDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupBCSummaryToolDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupBCSummaryToolDict()");
  G__set_cpp_environmentBCSummaryToolDict();
  G__cpp_setup_tagtableBCSummaryToolDict();

  G__cpp_setup_inheritanceBCSummaryToolDict();

  G__cpp_setup_typetableBCSummaryToolDict();

  G__cpp_setup_memvarBCSummaryToolDict();

  G__cpp_setup_memfuncBCSummaryToolDict();
  G__cpp_setup_globalBCSummaryToolDict();
  G__cpp_setup_funcBCSummaryToolDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBCSummaryToolDict();
  return;
}
class G__cpp_setup_initBCSummaryToolDict {
  public:
    G__cpp_setup_initBCSummaryToolDict() { G__add_setup_func("BCSummaryToolDict",(G__incsetup)(&G__cpp_setupBCSummaryToolDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBCSummaryToolDict() { G__remove_setup_func("BCSummaryToolDict"); }
};
G__cpp_setup_initBCSummaryToolDict G__cpp_setup_initializerBCSummaryToolDict;

