/********************************************************************
* BCMTFSystematicVariationDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BCMTFSystematicVariationDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBCMTFSystematicVariationDict();
extern void G__cpp_setup_inheritanceBCMTFSystematicVariationDict();
extern void G__cpp_setup_typetableBCMTFSystematicVariationDict();
extern void G__cpp_setup_memvarBCMTFSystematicVariationDict();
extern void G__cpp_setup_globalBCMTFSystematicVariationDict();
extern void G__cpp_setup_memfuncBCMTFSystematicVariationDict();
extern void G__cpp_setup_funcBCMTFSystematicVariationDict();
extern void G__set_cpp_environmentBCMTFSystematicVariationDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BCMTFSystematicVariation.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BCMTFSystematicVariationDictLN_string;
extern G__linked_taginfo G__BCMTFSystematicVariationDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BCMTFSystematicVariationDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMTFSystematicVariationDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BCMTFSystematicVariationDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMTFSystematicVariationDictLN_TH1D;
extern G__linked_taginfo G__BCMTFSystematicVariationDictLN_BCMTFSystematicVariation;
extern G__linked_taginfo G__BCMTFSystematicVariationDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR;
extern G__linked_taginfo G__BCMTFSystematicVariationDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
