/********************************************************************
* BCMTFTemplateDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BCMTFTemplateDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBCMTFTemplateDict();
extern void G__cpp_setup_inheritanceBCMTFTemplateDict();
extern void G__cpp_setup_typetableBCMTFTemplateDict();
extern void G__cpp_setup_memvarBCMTFTemplateDict();
extern void G__cpp_setup_globalBCMTFTemplateDict();
extern void G__cpp_setup_memfuncBCMTFTemplateDict();
extern void G__cpp_setup_funcBCMTFTemplateDict();
extern void G__set_cpp_environmentBCMTFTemplateDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BCMTFTemplate.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BCMTFTemplateDictLN_string;
extern G__linked_taginfo G__BCMTFTemplateDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BCMTFTemplateDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMTFTemplateDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BCMTFTemplateDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BCMTFTemplateDictLN_TH1D;
extern G__linked_taginfo G__BCMTFTemplateDictLN_BCMTFTemplate;
extern G__linked_taginfo G__BCMTFTemplateDictLN_vectorlETF1mUcOallocatorlETF1mUgRsPgR;
extern G__linked_taginfo G__BCMTFTemplateDictLN_reverse_iteratorlEvectorlETF1mUcOallocatorlETF1mUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
