//
// File generated by /home/osg/manageTier3SW/ATLASLocalRootBase/i686/root/5.34.07-i686-slc5-gcc4.3/bin/rootcint at Tue Jul  2 14:23:42 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BCTemplateFitterDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BCTemplateFitterDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void BCTemplateFitter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void BCTemplateFitter_Dictionary();
   static void *new_BCTemplateFitter(void *p = 0);
   static void *newArray_BCTemplateFitter(Long_t size, void *p);
   static void delete_BCTemplateFitter(void *p);
   static void deleteArray_BCTemplateFitter(void *p);
   static void destruct_BCTemplateFitter(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::BCTemplateFitter*)
   {
      ::BCTemplateFitter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::BCTemplateFitter),0);
      static ::ROOT::TGenericClassInfo 
         instance("BCTemplateFitter", "./BCTemplateFitter.h", 41,
                  typeid(::BCTemplateFitter), DefineBehavior(ptr, ptr),
                  0, &BCTemplateFitter_Dictionary, isa_proxy, 0,
                  sizeof(::BCTemplateFitter) );
      instance.SetNew(&new_BCTemplateFitter);
      instance.SetNewArray(&newArray_BCTemplateFitter);
      instance.SetDelete(&delete_BCTemplateFitter);
      instance.SetDeleteArray(&deleteArray_BCTemplateFitter);
      instance.SetDestructor(&destruct_BCTemplateFitter);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::BCTemplateFitter*)
   {
      return GenerateInitInstanceLocal((::BCTemplateFitter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BCTemplateFitter*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void BCTemplateFitter_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::BCTemplateFitter*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_BCTemplateFitter(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCTemplateFitter : new ::BCTemplateFitter;
   }
   static void *newArray_BCTemplateFitter(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::BCTemplateFitter[nElements] : new ::BCTemplateFitter[nElements];
   }
   // Wrapper around operator delete
   static void delete_BCTemplateFitter(void *p) {
      delete ((::BCTemplateFitter*)p);
   }
   static void deleteArray_BCTemplateFitter(void *p) {
      delete [] ((::BCTemplateFitter*)p);
   }
   static void destruct_BCTemplateFitter(void *p) {
      typedef ::BCTemplateFitter current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BCTemplateFitter

/********************************************************
* BCTemplateFitterDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBCTemplateFitterDict();

extern "C" void G__set_cpp_environmentBCTemplateFitterDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BCTemplateFitter.h");
  G__cpp_reset_tagtableBCTemplateFitterDict();
}
#include <new>
extern "C" int G__cpp_dllrevBCTemplateFitterDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BCTemplateFitter */
static int G__BCTemplateFitterDict_288_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCTemplateFitter* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCTemplateFitter[n];
     } else {
       p = new((void*) gvp) BCTemplateFitter[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BCTemplateFitter;
     } else {
       p = new((void*) gvp) BCTemplateFitter;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BCTemplateFitter* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new BCTemplateFitter((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) BCTemplateFitter((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetNTemplates());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetNTemplatesType((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetNSystErrors());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetNDF());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetNRatios());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TH1D>* pobj;
         vector<TH1D> xobj = ((BCTemplateFitter*) G__getstructoffset())->GetHistRatios1D();
         pobj = new vector<TH1D>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TH1D>* pobj;
         vector<TH1D> xobj = ((BCTemplateFitter*) G__getstructoffset())->GetTemplateHistogramContainer();
         pobj = new vector<TH1D>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<TF1>* pobj;
         vector<TF1> xobj = ((BCTemplateFitter*) G__getstructoffset())->GetTemplateFunctionContainer();
         pobj = new vector<TF1>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TH1D* pobj;
         TH1D xobj = ((BCTemplateFitter*) G__getstructoffset())->GetHistRatio1D((int) G__int(libp->para[0]));
         pobj = new TH1D(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCTemplateFitter*) G__getstructoffset())->GetUncertaintyHistogramExp());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BCTemplateFitter*) G__getstructoffset())->GetUncertaintyHistogramObsPosterior());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetIndexTemplate((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetIndexSystError((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetParIndexTemplate((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetParIndexTemplate((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetParIndexEff((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetParIndexSystError((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TH1D* pobj;
         TH1D xobj = ((BCTemplateFitter*) G__getstructoffset())->GetData();
         pobj = new TH1D(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetHistogramIndex((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->GetFunctionIndex((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<int>* pobj;
         vector<int> xobj = ((BCTemplateFitter*) G__getstructoffset())->GetTemplateParIndexContainer();
         pobj = new vector<int>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCTemplateFitter*) G__getstructoffset())->Expectation((int) G__int(libp->para[0]), *(vector<double>*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCTemplateFitter*) G__getstructoffset())->TemplateEfficiency((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, *(vector<double>*) libp->para[2].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCTemplateFitter*) G__getstructoffset())->TemplateProbability((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, *(vector<double>*) libp->para[2].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCTemplateFitter*) G__getstructoffset())->SetFlagPhysicalLimits((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCTemplateFitter*) G__getstructoffset())->SetFlagFixNorm((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCTemplateFitter*) G__getstructoffset())->SetNorm((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->SetData(*(TH1D*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->FixTemplateFunctions(*(vector<double>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->Initialize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->AddTemplate(*((TH1D*) G__int(libp->para[0])), (const char*) G__int(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->AddTemplate(*((TH1D*) G__int(libp->para[0])), (const char*) G__int(libp->para[1])
, (double) G__double(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->AddTemplate(*((TH1D*) G__int(libp->para[0])), (const char*) G__int(libp->para[1])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->AddTemplate(*((TF1*) G__int(libp->para[0])), (const char*) G__int(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (const char*) G__int(libp->para[4])));
      break;
   case 4:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->AddTemplate(*((TF1*) G__int(libp->para[0])), (const char*) G__int(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->AddTemplate(*((TF1*) G__int(libp->para[0])), (const char*) G__int(libp->para[1])
, (double) G__double(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->AddTemplate(*((TF1*) G__int(libp->para[0])), (const char*) G__int(libp->para[1])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->SetTemplateEfficiency((const char*) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->SetTemplateEfficiency((const char*) G__int(libp->para[0]), (double) G__double(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->SetTemplateEfficiency((const char*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->SetTemplateEfficiency((const char*) G__int(libp->para[0]), *((TH1D*) G__int(libp->para[1]))
, *((TH1D*) G__int(libp->para[2]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->AddSystError((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->AddSystError((const char*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->SetTemplateSystError((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, *((TH1D*) G__int(libp->para[2]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->ConstrainSum(*((vector<int>*) G__int(libp->para[0])), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->CalculateRatio((int) G__int(libp->para[0]), *((vector<int>*) G__int(libp->para[1]))
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])));
      break;
   case 3:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->CalculateRatio((int) G__int(libp->para[0]), *((vector<int>*) G__int(libp->para[1]))
, (double) G__double(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->CalculateRatio((int) G__int(libp->para[0]), *((vector<int>*) G__int(libp->para[1]))));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->CompareHistogramProperties(*((TH1D*) G__int(libp->para[0])), *((TH1D*) G__int(libp->para[1]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCTemplateFitter*) G__getstructoffset())->CalculateChi2(*(vector<double>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCTemplateFitter*) G__getstructoffset())->CalculateChi2Prob(*(vector<double>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCTemplateFitter*) G__getstructoffset())->CalculateMaxLike());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCTemplateFitter*) G__getstructoffset())->CalculatePValue());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BCTemplateFitter*) G__getstructoffset())->CalculateKSProb());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((BCTemplateFitter*) G__getstructoffset())->PrintStack((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((BCTemplateFitter*) G__getstructoffset())->PrintStack((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((BCTemplateFitter*) G__getstructoffset())->PrintStack();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      ((BCTemplateFitter*) G__getstructoffset())->PrintRatios((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (double) G__double(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((BCTemplateFitter*) G__getstructoffset())->PrintRatios((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((BCTemplateFitter*) G__getstructoffset())->PrintRatios((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((BCTemplateFitter*) G__getstructoffset())->PrintRatios();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->PrintTemplate((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BCTemplateFitter*) G__getstructoffset())->PrintTemp();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TH1D* pobj;
         TH1D xobj = ((BCTemplateFitter*) G__getstructoffset())->CreateErrorHist(*((TH1D*) G__int(libp->para[0])), *((TH1D*) G__int(libp->para[1])));
         pobj = new TH1D(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BCTemplateFitter*) G__getstructoffset())->PerformFit());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BCTemplateFitterDict_288_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TH1D* pobj;
         TH1D xobj = ((BCTemplateFitter*) G__getstructoffset())->CombineUncertainties((const char*) G__int(libp->para[0]));
         pobj = new TH1D(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BCTemplateFitterDict_288_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BCTemplateFitter* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BCTemplateFitter(*(BCTemplateFitter*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BCTemplateFitter G__TBCTemplateFitter;
static int G__BCTemplateFitterDict_288_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BCTemplateFitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BCTemplateFitter*) (soff+(sizeof(BCTemplateFitter)*i)))->~G__TBCTemplateFitter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BCTemplateFitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BCTemplateFitter*) (soff))->~G__TBCTemplateFitter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BCTemplateFitter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBCTemplateFitterDict {
 public:
  G__Sizep2memfuncBCTemplateFitterDict(): p(&G__Sizep2memfuncBCTemplateFitterDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBCTemplateFitterDict::*p)();
};

size_t G__get_sizep2memfuncBCTemplateFitterDict()
{
  G__Sizep2memfuncBCTemplateFitterDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBCTemplateFitterDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter))) {
     BCTemplateFitter *G__Lderived;
     G__Lderived=(BCTemplateFitter*)0x1000;
     {
       BCModel *G__Lpbase=(BCModel*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter),G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCModel),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       BCIntegrate *G__Lpbase=(BCIntegrate*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter),G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCIntegrate),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       BCEngineMCMC *G__Lpbase=(BCEngineMCMC*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter),G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCEngineMCMC),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBCTemplateFitterDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<double> >",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TTree*>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1D*>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH2D*>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCParameter*>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TNamed*>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BCModel*>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1D>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH1DcOallocatorlETH1DgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH1DcOallocatorlETH1DgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TF1>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETF1cOallocatorlETF1gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETF1cOallocatorlETF1gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETF1cOallocatorlETF1gRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<TH1D> >",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<TH1D> >",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<TH1D,allocator<TH1D> > >",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<int> >",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<int> >",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BCTemplateFitter */
static void G__setup_memvarBCTemplateFitter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter));
   { BCTemplateFitter *p; p=(BCTemplateFitter*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TH1D),-1,-1,2,"fHistData=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR),G__defined_typename("vector<TH1D>"),-1,2,"fTemplateHistogramContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETF1cOallocatorlETF1gRsPgR),G__defined_typename("vector<TF1>"),-1,2,"fTemplateFunctionContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR),G__defined_typename("vector<TH1D>"),-1,2,"fEffHistogramContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR),G__defined_typename("vector<TH1D>"),-1,2,"fEffErrHistogramContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgR),G__defined_typename("vector<std::vector<TH1D> >"),-1,2,"fSystErrorHistogramContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,2,"fTemplateNameContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,2,"fSystErrorNameContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fTemplateParIndexContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fHistogramIndexContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fFunctionIndexContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fEffParIndexContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fSystErrorParIndexContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,2,"fSystErrorTypeContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,2,"fTemplateTypeContainer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),G__defined_typename("vector<std::vector<int> >"),-1,2,"fConstraintSumIndices=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fConstraintSumMean=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"fConstraintSumRMS=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TH1D),-1,-1,2,"fHistNorm=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),G__defined_typename("vector<std::vector<int> >"),-1,2,"fIndicesRatios1D=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR),G__defined_typename("vector<TH1D>"),-1,2,"fHistRatios1D=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fFlagFixNorm=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"fFlagPhysicalLimits=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TH2D),-1,-1,2,"fUncertaintyHistogramExp=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TH2D),-1,-1,2,"fUncertaintyHistogramObsPosterior=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fNorm=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fNBins=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fXmin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fXmax=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBCTemplateFitterDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBCTemplateFitter(void) {
   /* BCTemplateFitter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter));
   G__memfunc_setup("BCTemplateFitter",1583,G__BCTemplateFitterDict_288_0_1, 105, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BCTemplateFitter",1583,G__BCTemplateFitterDict_288_0_2, 105, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter), -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNTemplates",1309,G__BCTemplateFitterDict_288_0_3, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNTemplatesType",1727,G__BCTemplateFitterDict_288_0_4, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - templatetype", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNSystErrors",1438,G__BCTemplateFitterDict_288_0_5, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNDF",504,G__BCTemplateFitterDict_288_0_6, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNRatios",992,G__BCTemplateFitterDict_288_0_7, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHistRatios1D",1439,G__BCTemplateFitterDict_288_0_8, 117, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR), G__defined_typename("vector<TH1D>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTemplateHistogramContainer",2989,G__BCTemplateFitterDict_288_0_9, 117, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR), G__defined_typename("vector<TH1D>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTemplateFunctionContainer",2885,G__BCTemplateFitterDict_288_0_10, 117, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlETF1cOallocatorlETF1gRsPgR), G__defined_typename("vector<TF1>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHistRatio1D",1324,G__BCTemplateFitterDict_288_0_11, 117, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TH1D), -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetUncertaintyHistogramExp",2705,G__BCTemplateFitterDict_288_0_12, 85, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TH2D), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetUncertaintyHistogramObsPosterior",3663,G__BCTemplateFitterDict_288_0_13, 85, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TH2D), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIndexTemplate",1620,G__BCTemplateFitterDict_288_0_14, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIndexSystError",1749,G__BCTemplateFitterDict_288_0_15, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParIndexTemplate",1911,G__BCTemplateFitterDict_288_0_16, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParIndexTemplate",1911,G__BCTemplateFitterDict_288_0_17, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParIndexEff",1356,G__BCTemplateFitterDict_288_0_18, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParIndexSystError",2040,G__BCTemplateFitterDict_288_0_19, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetData",666,G__BCTemplateFitterDict_288_0_20, 117, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TH1D), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHistogramIndex",1734,G__BCTemplateFitterDict_288_0_21, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - templatenumber", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFunctionIndex",1630,G__BCTemplateFitterDict_288_0_22, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - templatenumber", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTemplateParIndexContainer",2842,G__BCTemplateFitterDict_288_0_23, 117, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Expectation",1156,G__BCTemplateFitterDict_288_0_24, 100, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - binnumber u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TemplateEfficiency",1841,G__BCTemplateFitterDict_288_0_25, 100, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - templatenumber i - - 0 - binnumber "
"u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TemplateProbability",1981,G__BCTemplateFitterDict_288_0_26, 100, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - templatenumber i - - 0 - binnumber "
"u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFlagPhysicalLimits",2133,G__BCTemplateFitterDict_288_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFlagFixNorm",1385,G__BCTemplateFitterDict_288_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNorm",712,G__BCTemplateFitterDict_288_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - norm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetData",678,G__BCTemplateFitterDict_288_0_30, 105, -1, -1, 0, 1, 1, 1, 0, "u 'TH1D' - 11 - hist", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FixTemplateFunctions",2076,G__BCTemplateFitterDict_288_0_31, 105, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Initialize",1042,G__BCTemplateFitterDict_288_0_32, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddTemplate",1093,G__BCTemplateFitterDict_288_0_33, 105, -1, -1, 0, 4, 1, 1, 0, 
"u 'TH1D' - 0 - hist C - - 10 - name "
"d - - 0 '0' Nmin d - - 0 '0' Nmax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddTemplate",1093,G__BCTemplateFitterDict_288_0_34, 105, -1, -1, 0, 5, 1, 1, 0, 
"u 'TF1' - 0 - func C - - 10 - name "
"d - - 0 '0' Nmin d - - 0 '0' Nmax "
"C - - 10 '\"\"' options", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTemplateEfficiency",2141,G__BCTemplateFitterDict_288_0_35, 105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - name d - - 0 '1.' effmean "
"d - - 0 '0.' effsigma", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTemplateEfficiency",2141,G__BCTemplateFitterDict_288_0_36, 105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - name u 'TH1D' - 0 - eff "
"u 'TH1D' - 0 - efferr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddSystError",1222,G__BCTemplateFitterDict_288_0_37, 105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - errorname C - - 10 '\"gauss\"' errtype", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTemplateSystError",2085,G__BCTemplateFitterDict_288_0_38, 105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 - errorname C - - 10 - templatename "
"u 'TH1D' - 0 - parerror", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ConstrainSum",1254,G__BCTemplateFitterDict_288_0_39, 105, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<int,allocator<int> >' 'vector<int>' 0 - indices d - - 0 - mean "
"d - - 0 - rms", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateRatio",1421,G__BCTemplateFitterDict_288_0_40, 105, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - index u 'vector<int,allocator<int> >' 'vector<int>' 0 - indices "
"d - - 0 '-1.0' rmin d - - 0 '1.0' rmax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CompareHistogramProperties",2722,G__BCTemplateFitterDict_288_0_41, 105, -1, -1, 0, 2, 1, 1, 0, 
"u 'TH1D' - 0 - hist1 u 'TH1D' - 0 - hist2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateChi2",1236,G__BCTemplateFitterDict_288_0_42, 100, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateChi2Prob",1639,G__BCTemplateFitterDict_288_0_43, 100, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateMaxLike",1593,G__BCTemplateFitterDict_288_0_44, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculatePValue",1499,G__BCTemplateFitterDict_288_0_45, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateKSProb",1471,G__BCTemplateFitterDict_288_0_46, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCMCUserIterationInterface",2559,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PrintStack",1027,G__BCTemplateFitterDict_288_0_48, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 '\"stack.ps\"' filename C - - 10 '\"LE2E0D\"' options", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintRatios",1151,G__BCTemplateFitterDict_288_0_49, 121, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 '\"ratio.ps\"' filename i - - 0 '0' option "
"d - - 0 '0.' ovalue", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintTemplate",1353,G__BCTemplateFitterDict_288_0_50, 105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - name C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintTemp",931,G__BCTemplateFitterDict_288_0_51, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateErrorHist",1526,G__BCTemplateFitterDict_288_0_52, 117, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TH1D), -1, 0, 2, 1, 1, 0, 
"u 'TH1D' - 0 - hist u 'TH1D' - 0 - histerr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LogLikelihood",1318,(G__InterfaceMethod) NULL,100, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 11 - parameters", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("PerformFit",1022,G__BCTemplateFitterDict_288_0_54, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CombineUncertainties",2075,G__BCTemplateFitterDict_288_0_55, 117, G__get_linked_tagnum(&G__BCTemplateFitterDictLN_TH1D), -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("BCTemplateFitter", 1583, G__BCTemplateFitterDict_288_0_56, (int) ('i'), G__get_linked_tagnum(&G__BCTemplateFitterDictLN_BCTemplateFitter), -1, 0, 1, 1, 1, 0, "u 'BCTemplateFitter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BCTemplateFitter", 1709, G__BCTemplateFitterDict_288_0_57, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBCTemplateFitterDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBCTemplateFitterDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBCTemplateFitterDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_TH2D = { "TH2D" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_BCEngineMCMC = { "BCEngineMCMC" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR = { "vector<TTree*,allocator<TTree*> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TTree*,allocator<TTree*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR = { "vector<TH1D*,allocator<TH1D*> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1D*,allocator<TH1D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR = { "vector<TH2D*,allocator<TH2D*> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH2D*,allocator<TH2D*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR = { "vector<BCParameter*,allocator<BCParameter*> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCParameter*,allocator<BCParameter*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_BCIntegrate = { "BCIntegrate" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_BCModel = { "BCModel" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR = { "vector<TNamed*,allocator<TNamed*> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TNamed*,allocator<TNamed*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR = { "vector<BCModel*,allocator<BCModel*> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BCModel*,allocator<BCModel*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_BCTemplateFitter = { "BCTemplateFitter" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR = { "vector<TH1D,allocator<TH1D> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH1DcOallocatorlETH1DgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1D,allocator<TH1D> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlETF1cOallocatorlETF1gRsPgR = { "vector<TF1,allocator<TF1> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TF1,allocator<TF1> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgR = { "vector<vector<TH1D,allocator<TH1D> >,allocator<vector<TH1D,allocator<TH1D> > > >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<TH1D,allocator<TH1D> >,allocator<vector<TH1D,allocator<TH1D> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR = { "vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >" , 99 , -1 };
G__linked_taginfo G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBCTemplateFitterDict() {
  G__BCTemplateFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_TF1.tagnum = -1 ;
  G__BCTemplateFitterDictLN_TH1D.tagnum = -1 ;
  G__BCTemplateFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_TH2D.tagnum = -1 ;
  G__BCTemplateFitterDictLN_BCEngineMCMC.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_BCIntegrate.tagnum = -1 ;
  G__BCTemplateFitterDictLN_BCModel.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_BCTemplateFitter.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH1DcOallocatorlETH1DgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlETF1cOallocatorlETF1gRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBCTemplateFitterDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_TF1);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_TH2D);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_BCEngineMCMC);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlETTreemUcOallocatorlETTreemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETTreemUcOallocatorlETTreemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlETH1DmUcOallocatorlETH1DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH1DmUcOallocatorlETH1DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlETH2DmUcOallocatorlETH2DmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH2DmUcOallocatorlETH2DmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlEBCParametermUcOallocatorlEBCParametermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEBCParametermUcOallocatorlEBCParametermUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_BCIntegrate);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_BCModel);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlETNamedmUcOallocatorlETNamedmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETNamedmUcOallocatorlETNamedmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlEBCModelmUcOallocatorlEBCModelmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEBCModelmUcOallocatorlEBCModelmUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_BCTemplateFitter),sizeof(BCTemplateFitter),-1,34048,(char*)NULL,G__setup_memvarBCTemplateFitter,G__setup_memfuncBCTemplateFitter);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlETH1DcOallocatorlETH1DgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETH1DcOallocatorlETH1DgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlETF1cOallocatorlETF1gRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlETF1cOallocatorlETF1gRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlETH1DcOallocatorlETH1DgRsPgRcOallocatorlEvectorlETH1DcOallocatorlETH1DgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__BCTemplateFitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupBCTemplateFitterDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupBCTemplateFitterDict()");
  G__set_cpp_environmentBCTemplateFitterDict();
  G__cpp_setup_tagtableBCTemplateFitterDict();

  G__cpp_setup_inheritanceBCTemplateFitterDict();

  G__cpp_setup_typetableBCTemplateFitterDict();

  G__cpp_setup_memvarBCTemplateFitterDict();

  G__cpp_setup_memfuncBCTemplateFitterDict();
  G__cpp_setup_globalBCTemplateFitterDict();
  G__cpp_setup_funcBCTemplateFitterDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBCTemplateFitterDict();
  return;
}
class G__cpp_setup_initBCTemplateFitterDict {
  public:
    G__cpp_setup_initBCTemplateFitterDict() { G__add_setup_func("BCTemplateFitterDict",(G__incsetup)(&G__cpp_setupBCTemplateFitterDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBCTemplateFitterDict() { G__remove_setup_func("BCTemplateFitterDict"); }
};
G__cpp_setup_initBCTemplateFitterDict G__cpp_setup_initializerBCTemplateFitterDict;

